# Generated by Django 2.1.7 on 2019-02-17 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorsDb',
            fields=[
                ('doc_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('specialization', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('availability', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
                ('desc', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='availability',
            field=models.ManyToManyField(related_name='doc_availability', to='goplannr.DoctorsDb'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doc_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goplannr.DoctorsDb'),
        ),
    ]
