# Generated by Django 2.1.7 on 2019-02-18 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goplannr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='availability',
        ),
    ]
